### ISSUE TITLE
Step size alteration?

### ISSUE THREAD

**Issue by shrungBhatt** [GuilhE/android-seekbar-ranged-view#1]
Is there any way I can change the step size of the range bar?

**Comment by GuilhE** [comment]
Hello Shrung,
Sorry but that's not available at the moment. You're welcome to collaborate in this project and develop such feature.

**Comment by shrungBhatt** [comment]
Well its alright but, How are you changing the values when we slide the thumbNail. I can try to change it and if I get successful I can request a push here.
But I cannot understand, how are you incrementing the values ? Please can you point me to the exact method that does this?

**Comment by GuilhE** [comment]
It starts with: https://github.com/GuilhE/android-seekbar-ranged-view/blob/a410f9df7d9cacbb1c298f66230ff09c0b89d900/seekbar-ranged-view/src/main/java/com/github/guilhe/rangeseekbar/SeekBarRangedView.java#L715

So we are dragging a thumb and when we release our finger occurs a `MotionEvent.ACTION_UP` that will call a  `trackTouchEvent(event);`.
That method: https://github.com/GuilhE/android-seekbar-ranged-view/blob/a410f9df7d9cacbb1c298f66230ff09c0b89d900/seekbar-ranged-view/src/main/java/com/github/guilhe/rangeseekbar/SeekBarRangedView.java#L579

will then capture the X value and will convert it from "screen" to "view" value (normalized). That will cause an` invalidate()` which will call `onDraw`. 

So as you can see, there's no "increment" value, we track the UI View being moved and when it stops we extract its value and then convert to something we can work with in a desired _value space_ between A and B.
For example, if we want a value in a _value space_ between minVal and maxVal (ex, 0 and 100) we call:
https://github.com/GuilhE/android-seekbar-ranged-view/blob/a410f9df7d9cacbb1c298f66230ff09c0b89d900/seekbar-ranged-view/src/main/java/com/github/guilhe/rangeseekbar/SeekBarRangedView.java#L532

Check out the following methods: **normalizedToValue**, **valueToNormalized**, **normalizedToScreen** and **screenToNormalized**. They all convert a value to a different _value space_.

And that's it.

I guess you'll have to create some kind of "snap" behaviour inside `MotionEvent.ACTION_MOVE`  from `onTouchEvent` to achieve what you want.

**Comment by GuilhE** [comment]
This feature is done, check for v2.0.0
