### ISSUE TITLE
CHANGELOG

### ISSUE THREAD

**Issue by adamstyrc** [GuilhE/android-seekbar-ranged-view#13]
Hey, I really like the lib and I use it on production ! :)

Could you indicate some changelog? What changed in version 2.0.3 e.g. ?

**Comment by GuilhE** [comment]
Hello @adamstyrc and thanks for your support :)
The biggest changes in version 2.X is "progress-by-step" where you can define "auto-snap" steps. 
The following versions improve:
- Thumbs by drawable better support
- Attr.xml refactor to avoid duplicated attr names with other libs

**Comment by adamstyrc** [comment]
Yes, I'm actually using it as Int picker instead of Float (e.g. 0-11) :) so I guess I could switch to steps :>

Coming new improvements are also great because I try to put vector drawable / shape drawable for Thumbs. In order to omit a crash I need to pass a bitmap instead =) Thx!

Could you add this CHANGELOG to github sources ?
