### ISSUE TITLE
1.0.3 doesn't reference as 1.0.2?

### ISSUE THREAD

**Issue by emailsubjekt** [GuilhE/android-seekbar-ranged-view#3]
Is there a change from 1.0.2 to 1.0.3? After I change to 1.0.3 I can't get a reference anymore and the app won't start.

**Comment by GuilhE** [comment]
Yes, a path rename from:
import com.github.guilhe.rangeseekbar.SeekBarRangedView;
To:
import com.github.guilhe.views.SeekBarRangedView;
