### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by Ora-Kool** [GuilhE/android-seekbar-ranged-view#7]
When i use the custom:thumbsResource, i get a null pointer exception in the SeekBarRangedView class

**Comment by GuilhE** [comment]
Hello Ora-Kool,
Can you provide some stacktrace and your layout implementation?

The sample app uses: `custom:thumbsResource="@mipmap/ic_launcher_round"/>` with no problem.

Thanks.

**Comment by GuilhE** [comment]
7 days without activity, thread closed
