### ISSUE TITLE
No virtual method getColor()

### ISSUE THREAD

**Issue by adamstyrc** [GuilhE/android-seekbar-ranged-view#9]
I'd like to report a bug that occured for Android 5 (motorola Moto X (1st Gen)) when using 
`setProgressColorResource`

> java.lang.NoSuchMethodError: No virtual method getColor(I)I in class Landroid/content/Context; or its super classes (declaration of 'android.content.Context' appears in /system/framework/framework.jar)
> at com.github.guilhe.views.SeekBarRangedView.setProgressColorResource + 460(SeekBarRangedView.java:460)
> 

**Context.getColor(int)** method is from SDK 23 so please switch to **ContextCompat.getColor(this, colorId)** :)

**Comment by GuilhE** [comment]
Hello Adam and thanks for you PR.
The idea is to keep at minimum the project dependencies, that's why I didn't import the `support-compat` in the first place.

In the code you can see that I have a comment and  `@RequiresApi(api = Build.VERSION_CODES.M):`
```
    /**
     * You can simulate the use of this method with by calling {@link #setProgressColor(int)} with ContextCompat:
     * setProgressColor(ContextCompat.getColor(resId));
     */
    @RequiresApi(api = Build.VERSION_CODES.M)
    public void setProgressColorResource(@ColorRes int resId) {
        setProgressColor(getContext().getColor(resId));
    }
```

If you're compiling for min **API >= M** you won't have a problem. Otherwise you should use `setProgressColor(ContextCompat.getColor(resId)` (this delegates the dependency to your project)

Cheers.

**Comment by adamstyrc** [comment]
When you look into the method definion you can see it, but compiler didn't highlight this usage with any warning/error though my **min** is **21** ;)

Yes, adding dependency would be maybe too much, libraries usually include some custom helper methods. Depends how you prefer :)

I already use `setProgressColor()` but had colleced some crashes.

Thx for the work anyway!

**Comment by GuilhE** [comment]
> When you look into the method definion you can see it, but compiler didn't highlight this usage with any warning/error though my **min** is **21** ;)

Really? Now that's strange, I've added the annotation `@RequiresApi(api = Build.VERSION_CODES.M)` (M = 23) to prevent situations like these.

> Thx for the work anyway!

Hey np, thanks for using it :)
